### ISSUE TITLE
Docker image for adroit?

### ISSUE THREAD

**Issue by watchernyu** [facebookresearch/RRL#3]
Hi! I'm just curious if you have been using docker containers to run experiments with Adroit? When I tried the rendering in a docker container (using a nvidia base image), it seems this line `img = e.env.sim.render()` can be very slow. And it is unclear what the reason is... 

If you have used docker then it would be great if you can share any information about the container you used... that would be really useful! Really appreciate your help!

**Comment by vikashplus** [comment]
We haven't used docker in this project. We relied on conda + hydra for dependency managements and experimentation. 

Rendering is handled by MuJoCoPy. The specifics behind rendering are independent of Adroit or any other details of this project. I'd recommend checking for help more generally over the internet on the topic with keywords -- `gpu`, `rendering`, `mujocoPy`, `docker`.

**Comment by watchernyu** [comment]
After looking at the source code of mujoco_py, I found that the problem comes from the fact that when mujoco_py is built, it might not correctly detect a nvidia gpu is available and then will build the CPU version of mujoco without giving any warning messages. Things seem to be working now. Thank you so much again for helping me with this issue!
