### ISSUE TITLE
Training Runtime is high

### ISSUE THREAD

**Issue by meghbhalerao** [facebookresearch/RRL#5]
Dear Authors,

Thank you for the work and making the source code publicly available!
I had a quick question regarding the amount of time taken to train the policy. For example I am looking at the logs here - https://github.com/facebookresearch/RRL/blob/main/experiment_logs/RRL/hammer-v0/hammer-v0_obstate_resnet34_top_fx_seed10/logs/log.csv - I see that the `time_sampling` is approximately 500 seconds for each iteration and there are 300 iterations so the total time is `300 * 500/ 3600 Hours` which is approximately 41 hours. I see that in the paper the runtime has been reported as around 6 hours - 
<img width="384" alt="Screenshot 2023-01-29 at 14 00 01" src="https://user-images.githubusercontent.com/33202960/215357952-f840767e-fb55-4c83-8bf0-eed6187df9de.png">
I am not sure if I am comparing the correct plots - I looked at the logs for all the tasks and it seems like the `time_sampling` is around 500 to 600 seconds for all the different tasks.
In my machine the sampling time for the hammer task for 1 iteration is around 1600 seconds - my specifications are as follows on an ubuntu machine - 

```
Architecture:                    x86_64
 Intel(R) Core(TM) i9-9960X CPU 
                                 @ 3.10GHz
CPU(s):                          32
```

When I run the training job I see that my CPU cores are completely occupied 100 % on all 32 cores (which I think is expected since trajectory sampling seems to be a CPU intensive task according to the multiprocessing routine which is in the code). I am not sure if I could find the machine specifications on the paper?

Please do let me know and thanks for your time.

**Comment by ShahRutav** [comment]
Hi,

There are multiple pointers to address here

1.  The sampling time in log files are not comparable because I had launched multiple experiments in the same system.
2.  The compute calculation in the figure are done using 1 million samples without any parallel processing and in a system with no other experiments running simultaneously. Details in Section 7.9 
3.  1600 seconds per iteration is pretty slow, are you using GPU for mujoco_py rendering and encoding resent features?

**Comment by meghbhalerao** [comment]
Thanks. 
When you mention samples, does that mean your sample_mode is 'samples' and not 'trajectories'? I am using 'trajectories' which is the default in the job_script.py
Yes, I am using a GPU for the encoding the environment using resnet, but I am not doing the mujoco_py rendering right now, I am trying to get the samples vs success_rate plots. Also, the 1600 seconds is to sample the trajectories, not the iteration time exactly, although I believe that they are similar since the sampler rollouts take the most time.
Also, I am using the exact same config file provided in the configs folder under examples. Also, I just tried it for resnet50, and it is around 2k seconds to gather the samples.

**Comment by ShahRutav** [comment]
'samples' is the number of times agent interacts with the environment.

I believe your bottleneck is image rendering in mujoco_py. Can you confirm if mujoco_py is running using CPU/GPU?

**Comment by meghbhalerao** [comment]
Thanks. 

The rendering is happening at this line if I am not mistaken - https://github.com/facebookresearch/RRL/blob/main/rrl/multicam.py#L80 - is there any way to ensure that it will happen on GPU? I see that a device_id argument is being passed, but I am not sure if that ensures a GPU render.

**Comment by ShahRutav** [comment]
it depends on how you installed mujoco_py. A simple quick test  `python -c "import mujoco_py; print(mujoco_py.cymj)"`. 

Feel free to take a look at this [repository](https://github.com/ShahRutav/mujoco-py_rendering)

**Comment by meghbhalerao** [comment]
I get this - `<module 'cymj' from '/home/megh98/anaconda3/envs/rrl/lib/python3.6/site-packages/mujoco_py/generated/cymj_2.0.2.13_36_linuxcpuextensionbuilder_36.so'>`

this is probably only cpu.

**Comment by ShahRutav** [comment]
Yes. You should install `mujoco_py` with GPU support

**Comment by meghbhalerao** [comment]
Thanks. Closing this issue now. Relevant links are present here for GPU install of Mujoco - https://github.com/ShahRutav/mujoco-py_rendering - as @ShahRutav  pointed out.
